#!/usr/bin/ruby

require '../lib/fcm-agent-tools.rb'

f = FcmAgent.new

installed = {}

r = IO.popen("rpm -qa")
r.readlines.each { |k| installed[k.chomp] = true }
r.close

exitcode = 0
f.filedata.each_line do |pkg|
  pkg.chomp!
  next if installed[pkg]
  unless system("yum", "-y", "install", pkg)
    exitcode = 1
  end
end

exit(exitcode)
